import { Metadata } from 'next'
import { ReactNode } from 'react'

interface PokemonLayout {
    children: ReactNode
}

export const metadata: Metadata = {
    title: 'Pokemon - Pikachu',
    description: 'Generated by create next app',
}

export default function PokemonLayout({ children }: PokemonLayout) {
    return (
        <div>
            <h3>Pikachu Layout</h3>
            {children}
        </div>
    )
}